services:

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app:cached
    env_file:
      - .env   # ✅ Neon connection string will be used
    restart: on-failure

  frontend:
    build:
      context: "./app/rag frontend/frontend"
      dockerfile: "../../../docker/Dockerfile.frontend"
    ports:
      - "5173:5173"
    depends_on:
      - api
    restart: on-failure